### ISSUE TITLE
Question: are compressed chunks send over the wire in compressed form?

### ISSUE THREAD

**Issue by royerloic** [manzt/simple-zarr-server#4]
Really a question, but if the answer is no, there might be of course an opportunity for performance boost,
a since for example for our data we easily achieve a 15x compression...

**Comment by joshmoore** [comment]
My guess would be yes. There doesn't look to be any modification of the metadata, and so the client implementations will be expecting to perform the decoding.

**Comment by manzt** [comment]
Yep! simple-zarr-server just forwards the encoded chunks to the client. At one point i'd explored implementing some time of "middleware" in simple-zarr-server, but now I think that kind of functionality could just live in a custom store.
